version: "3.8"

services:
  backend:
    build:
      context: ./api
    container_name: qr-backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - qr-net

  frontend:
    build:
      context: ./front-end-nextjs
    container_name: qr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./front-end-nextjs:/app
      - /app/node_modules  
    command: npm run dev
    networks:
      - qr-net

networks:
  qr-net:
    driver: bridge
