# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
spec:
  selector:
    app: qr-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort  # To pozwoli na dostęp z przeglądarki